### ISSUE TITLE
Preferred language

### ISSUE THREAD

**Issue by FlameSA** [adriantc/UTF-8SubtitlesConverter.bundle#3]
Hello,
firstly thank you so much for updating this plugin, this is mega helpful for me and others

I noticed that the option for adding a preferred language is not working while choosing the conversion result to be: Overwrite original file make a backup/Don't
it's only working when the option: create a new file as original 
but when I choose this option 
plex will always force the Real original sub and ignore the new one even tho it's preferred to use in plex subtitle language settings
so if you update this to 
overwrite and add a language code
would be much appreciated

again
thank you so much for updating this

**Comment by adriantc** [comment]
Hi! Sorry but I don't understand the problem. There is already an option to create a new file with the preferred language code... doesn't that work for you?
